server:
  port: 9003
renthouse:
  search:
    init:
      enabled: true # 配置是否需要初始化索引，创建和设置映射。默认为false
spring:
  profiles:
    active: mongodb,bannerNginx
  application:
    name: renthouse-search
  elasticsearch:
    rest:
      uris: http://192.168.66.123:9200
eureka:
  client:
    service-url:
      defaultZone: http://192.168.66.123:8761/eureka/
  instance:
    prefer-ip-address: true